In [3]:
import numpy as np
ar1=np.arange(30)

In [4]:
ar1
len(ar1)

30

In [8]:
reshaped_array=ar1.reshape(30,1)

In [9]:
reshaped_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [ ]:
#identity ma

In [10]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:

np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [15]:
np.identity(5,dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#slicing multidimensional 

In [19]:
ar2=np.arange(25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ar2.shape

(5, 5)

In [21]:
#to performm multidimentional slicing
ar2=np.arange(25).reshape(5,5)#ar2[rows,coloums,step]
#ar2[row_start:row_end,col_start,col_end,step]
ar2[0:3,1:4]


array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [23]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [24]:
ar2[-4:-2]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [ ]:
#tasks
#1.)to print 27,28,37,38--->
#2.)print 34,35,44,45
#3.)print 18 19
#4.)print 31,31,40,41

In [27]:
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
#linspace
np.sum(ar3)

1225

In [29]:
#to add based on cloumn wise axis=0
np.sum(ar3,axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [30]:
#to add based on row wiseaxis=1
np.sum(ar3,axis=1)


array([ 45, 145, 245, 345, 445])

In [ ]:
important points
1.mean-->average
2.median-->center value
3.mode-->max num of repeated elements
4.variance-->median /total num of elements
5.std deviation-->sqrt of variance


In [31]:
#linspace
it used to print the evenly seperated pointed
#between 2 range of values
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [34]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [35]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [36]:
np.linspace(1,10,4,dtype=int)#--linspace(start,en,num of values)

array([ 1,  4,  7, 10])

In [38]:
np.linspace(12,30,12,retstep=True)


(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [41]:
#random module
#np.random.randit(start,end)
#to generate random numbers between the range
np.random.randint(40)

30

In [43]:
np.random.randint(20,30)

24

In [44]:
np.random.randint(20,30,3) to get the 20 and 30  of 3 random values#

array([24, 27, 24])

In [46]:
#rand()-->
#to get the randomly generated values from 0to1,based on
#uniform distribution
np.random.rand(4)

array([0.06321646, 0.99839413, 0.71421917, 0.77295154])

In [47]:
np.random.rand(10)

array([0.66509445, 0.74889996, 0.31604465, 0.67474284, 0.21438082,
       0.64143985, 0.13515284, 0.05318982, 0.05489477, 0.67917759])

In [48]:
np.random.rand(3,4) by 3 rows and 4 columns  it will take number wise

array([[0.41953177, 0.36112501, 0.34563538, 0.8672599 ],
       [0.6761098 , 0.2728707 , 0.13804364, 0.71864921],
       [0.5930002 , 0.95116302, 0.99284753, 0.45279351]])

In [49]:
to get the randomly generated values from 0to1,based on
#Normalied distribution

SyntaxError: invalid decimal literal (1592410368.py, line 1)

In [50]:
np.random.randn(5)

array([-0.51041933, -2.49152613,  0.07047474,  0.58102971,  0.50117562])

In [51]:
np.random.randn(5,4)

array([[ 2.03433408,  1.18566015,  0.62181723,  0.7665954 ],
       [ 2.0828781 , -0.06999792,  0.48753165, -0.46611016],
       [ 0.42234113, -1.61757677,  0.17093907,  0.19641231],
       [-0.10478362,  0.5278155 ,  1.41315472,  0.38565015],
       [-0.15822081, -1.71342082,  0.93415324, -0.61088251]])

In [52]:
#find the min and max values
ar3.min()

0

In [53]:
ar3.max()

49

In [57]:
#to  find the index of min values
l1=[56,89,90,67,45]
print(l1.index(45))
print(l1.index(90))

4
2


In [56]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [58]:
#argmin and max is inbulit function used to find min and max termms of an array using list converted an array
l1=[56,89,90,67,45]
np1=np.array(l1)
print(np1.argmin())#to find the mmin values index position in array
print(np1.argmax())#to find the max values ndexposition in array

4
2


In [59]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [60]:
 np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [68]:

np2=np.array([1,2,3])
np3=np.array([4,5,6])
#(1*4)+(2*5)+(3*6) =4+10+18 =>32 find logic 
ar5=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])
ar5

32

In [69]:
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
np.sum((np2*np3))

32

In [ ]:
#fname=np.array(["sita","fn1","fn2"],dtype=str)
#lname=np.array(['T',"ln1","ln2"],dtype=str)

In [ ]:
np1=np.array([1,34,56,78,np.nan,np.nan])

In [70]:
np1[np.isnan(np1)]

array([], dtype=int32)

In [71]:
np1[~np.isnan(np1)] to delete nan value

array([56, 89, 90, 67, 45])